version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: crm-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    container_name: crm-redis
    ports:
      - "6379:6379"
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    
    ports: 
      - "4000:4000"
    container_name: crm-api
    volumes:
      - /app/prisma
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://root:123456@db:5432/crmdb
      PORT: 4000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    container_name: crm-client
    depends_on:
      - api
    environment:
      PORT: 3000
      VITE_API_URL: http://localhost:4000
volumes:
  postgres-data:
    external: false
